import { Document } from 'mongoose';
import { IProject } from '../models/Project';

export type IProjectInput = Omit<IProject, keyof Document>;

export const initialProjectsData: IProjectInput[] = [
  {
    title: 'TALENT AI',
    slug: 'talent-ai',
    tagline: 'AI-Powered Resume Search, ATS & Technical Evaluation Platform',
    description: 'Engineered an AI-powered ATS automating resume parsing, candidate ranking, skill extraction, recruiter summaries, Monaco Editor coding sandbox, WebRTC video interviews, and automated PDF offer letters.',
    category: 'Full Stack',
    featured: true,
    coverImage: '/project-images/talentai.png',
    images: ['/project-images/talentai.png'],
    year: '2026',
    role: 'Full Stack & AI Engineer',
    techStack: ['Full Stack', 'MERN Stack', 'Gemini AI', 'WebRTC', 'Socket.IO', 'Tailwind CSS'],
    liveUrl: 'https://talentai.sumann.in/',
    githubUrl: 'https://github.com/sumancpp/ai-resume-ats',
    overview: 'TALENT AI is a production-ready ATS platform that automates candidate scoring, skill matching, live Monaco editor execution, and real-time WebRTC technical interviews using Google Gemini AI.',
    order: 1,
  },
  {
    title: 'BAATCHEET',
    slug: 'baatcheet',
    tagline: 'AI Powered Real-Time Chat & Collaboration Platform',
    description: 'Built a scalable real-time messaging platform supporting JWT auth, WebRTC audio/video calling, browser screen sharing, collaborative whiteboard, disappearing Ghost Ink messages, and Gemini AI code review.',
    category: 'Full Stack',
    featured: true,
    coverImage: '/project-images/baatcheet-logo.png',
    images: ['/project-images/baatcheet-logo.png'],
    year: '2025',
    role: 'Full Stack Software Engineer',
    techStack: ['Full Stack', 'MERN Stack', 'Socket.IO', 'WebRTC', 'Google Gemini AI', 'Cloudinary'],
    liveUrl: 'https://baatcheet.sumann.in/',
    githubUrl: 'https://github.com/sumancpp/RealTimeChat',
    overview: 'BAATCHEET is a high-velocity collaboration platform incorporating bidirectional Socket.IO signaling, WebRTC P2P media streams, and AI code analysis.',
    order: 2,
  },
  {
    title: 'SHIFRA 2.0',
    slug: 'shifra-2',
    tagline: 'Voice-Powered Virtual Assistant with Real-Time Speech Recognition & Synthesis',
    description: 'Engineered a voice-powered virtual assistant built with React.js, Speech Recognition, and Web Speech API. Features real-time voice input transcription, AI responses, microphone permission handling, and dynamic UI states.',
    category: 'Frontend',
    featured: true,
    coverImage: '/project-images/Shifra2.0.png',
    images: ['/project-images/Shifra2.0.png'],
    year: '2026',
    role: 'Frontend & Web Speech Engineer',
    techStack: ['Frontend', 'React.js', 'Web Speech API', 'Speech Recognition', 'AI Integration', 'Tailwind CSS'],
    liveUrl: 'https://virtual-assistant-eight-omega.vercel.app/',
    githubUrl: 'https://github.com/sumancpp/React-Projects/tree/main/Virtual%20Assistant',
    overview: 'SHIFRA 2.0 delivers hands-free voice commands, AI context memory, and synthesis playback.',
    order: 3,
  },
  {
    title: 'SUMAN CAFE (FOOD DELIVERY)',
    slug: 'food-delivery',
    tagline: 'Responsive Food Delivery Platform with Category Filtering & Dynamic Cart System',
    description: 'Built a feature-rich Food Delivery application in React.js featuring category-based food filtering, dynamic cart management with real-time add/remove calculations, custom timed toast notifications, Redux + Context state management, and responsive UI design.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/Food_delivery.png',
    images: ['/project-images/Food_delivery.png'],
    year: '2026',
    role: 'Frontend React Engineer',
    techStack: ['Frontend', 'React.js', 'Redux', 'Context API', 'Tailwind CSS', 'Netlify'],
    liveUrl: 'https://suman-cafe.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/React-Projects/tree/main/Food%20Delivery',
    overview: 'Dynamic food ordering web application with reactive cart calculation and custom notifications.',
    order: 4,
  },
  {
    title: 'BACKGROUND REMOVER TOOL',
    slug: 'background-remover',
    tagline: 'Instant Web-Based Background Removal Tool with Real-Time Preview & Transparent PNG Download',
    description: 'Built a web-based background removal tool using Vanilla JavaScript, HTML5, CSS3, and the Remove.bg API. Supports instant image file upload via FileReader API, before/after side-by-side preview, transparent PNG download, and responsive UI transitions.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/RemoveBg.png',
    images: ['/project-images/RemoveBg.png'],
    year: '2026',
    role: 'Frontend Engineer',
    techStack: ['Frontend', 'JavaScript (ES6+)', 'HTML5 & CSS3', 'Remove.bg API', 'FileReader API', 'Netlify'],
    liveUrl: 'https://remove-image-background-and-download.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/Projects/tree/main/Image%20Background%20Remover',
    overview: 'Client-side file processing and API integration tool for transparent image output.',
    order: 5,
  },
  {
    title: 'YOUR GYM CENTER',
    slug: 'your-gym',
    tagline: 'Sleek, Responsive & Interactive Fitness & Gym Website built from scratch',
    description: 'Designed and developed a modern fitness and gym portal using HTML5, CSS3, and Vanilla JavaScript. Features interactive membership registration forms, trainer profile showcases, workout program galleries, smooth scrolling, and custom CSS keyframe animations.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/gym.png',
    images: ['/project-images/gym.png'],
    year: '2026',
    role: 'Frontend Designer & Developer',
    techStack: ['Frontend', 'HTML5', 'CSS3 Animations', 'JavaScript (ES6+)', 'Responsive Design', 'Netlify'],
    liveUrl: 'https://your-gym-center.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/Projects/tree/main/Your%20Gym',
    overview: 'Interactive responsive gym portal with membership forms and trainer showcases.',
    order: 6,
  },
  {
    title: 'REAL-TIME WEATHER APP',
    slug: 'weather-app',
    tagline: 'Live Weather Forecasting Application with Dynamic City Search & Atmospheric Metrics',
    description: 'Engineered a real-time Weather Forecasting application using HTML5, CSS3, Vanilla JavaScript, and the OpenWeatherMap REST API. Features location-based weather fetching, temperature, humidity, wind speed, atmospheric pressure metrics, and dynamic climate status icons.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/weather.png',
    images: ['/project-images/weather.png'],
    year: '2026',
    role: 'Frontend API Developer',
    techStack: ['Frontend', 'JavaScript (ES6+)', 'REST APIs', 'Fetch API', 'HTML5 & CSS3', 'Netlify'],
    liveUrl: 'https://weather-app-by-suman.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/Projects/tree/main/Weather%20App',
    overview: 'Real-time weather tracking utility with global city search capabilities.',
    order: 7,
  },
  {
    title: 'RESPONSIVE SNAKE GAME',
    slug: 'snake-game',
    tagline: 'Classic Interactive Arcade Snake Game with Cross-Device Touch & Keyboard Controls',
    description: 'Engineered a fully responsive, cross-device Snake game using HTML5, CSS3, and Vanilla JavaScript. Features real-time collision detection, dynamic score tracking, adaptive grid rendering, touch gesture controls for mobile/tablet, and keyboard arrow controls for desktop.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/snakeGame.png',
    images: ['/project-images/snakeGame.png'],
    year: '2026',
    role: 'Game Logic & Web Developer',
    techStack: ['Frontend', 'JavaScript (ES6+)', 'HTML5 Canvas', 'Game Development', 'Responsive Design', 'Netlify'],
    liveUrl: 'https://suman-snake-game.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/Projects/tree/main/Snake%20Game',
    overview: 'HTML5 canvas arcade game with cross-device swipe and keyboard controls.',
    order: 8,
  },
  {
    title: 'TIC TAC TOE GAME',
    slug: 'tic-tac-toe',
    tagline: 'Interactive 2-Player & AI Web Game with Win Pattern Detection & Score Tracking',
    description: 'Built a classic interactive Tic Tac Toe web game using HTML5, CSS3, and Vanilla JavaScript. Features real-time win condition evaluation algorithm, interactive turn indicators, game reset capabilities, score tracking, and responsive UI design.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/TicTacToe.png',
    images: ['/project-images/TicTacToe.png'],
    year: '2026',
    role: 'Frontend Developer',
    techStack: ['Frontend', 'JavaScript (ES6+)', 'HTML5 & CSS3', 'Game Logic', 'DOM Manipulation', 'Netlify'],
    liveUrl: 'https://aquamarine-khapse-997869.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/Projects/tree/main/Tic%20Tac%20Toe%20Game',
    overview: '2-Player matrix win detection web game.',
    order: 9,
  },
  {
    title: 'REAL-TIME EMAIL VALIDATOR',
    slug: 'email-validator',
    tagline: 'Real-Time Email Address Verification & MX Record/Syntax Checking Utility',
    description: 'Engineered a web-based Email Validation tool using HTML5, CSS3, and Vanilla JavaScript. Verifies email address syntax, domain MX record validity, disposable email detection, and delivers instant visual status feedback.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/email.png',
    images: ['/project-images/email.png'],
    year: '2026',
    role: 'Frontend Developer',
    techStack: ['Frontend', 'JavaScript (ES6+)', 'Regex Validation', 'API Integration', 'HTML5 & CSS3', 'Netlify'],
    liveUrl: 'https://jocular-souffle-aaf03b.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/Projects/tree/main/Email%20Validator',
    overview: 'Email verification utility with RFC syntax and disposable domain checking.',
    order: 10,
  },
  {
    title: 'SPOTIFY MUSIC PLAYER',
    slug: 'spotify-player',
    tagline: 'Functional Spotify Web Player Clone with Custom Seek Bar, Playlist Tracks & Audio Controls',
    description: 'Engineered a functional Spotify web application using HTML5, CSS3, and Vanilla JavaScript. Features real-time audio playback controls (Play, Pause, Next, Previous), custom seek bar time updates, volume sliders, playlist track switching, and dark Spotify UI styling.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/spotify.png',
    images: ['/project-images/spotify.png'],
    year: '2026',
    role: 'Frontend Developer',
    techStack: ['Frontend', 'JavaScript (ES6+)', 'HTML5 Audio API', 'Spotify UI', 'CSS Grid & Flexbox', 'Netlify'],
    liveUrl: 'https://stately-llama-c0f7e4.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/Projects/tree/main/Spotify',
    overview: 'HTML5 audio web player with custom controls and dark theme.',
    order: 11,
  },
  {
    title: 'PRIVATE PROPERTY RENTAL',
    slug: 'property-rental',
    tagline: 'Clean & Responsive Property Discovery & Listing Platform',
    description: 'Built a Private Property Rental platform allowing users to discover and list diverse rental properties (Houses, Rooms, Cabins, Farm & Pool Houses, Shops, Forest Houses) with clean UI, search filtering, direct Gmail contact, and smooth animations.',
    category: 'Frontend',
    featured: false,
    coverImage: '/project-images/private-property-rental.png',
    images: ['/project-images/private-property-rental.png'],
    year: '2025',
    role: 'Frontend React Developer',
    techStack: ['Frontend', 'React.js', 'React Router', 'Context API', 'UI/UX Design', 'Tailwind CSS'],
    liveUrl: 'https://private-property-rental-by-suman.netlify.app/',
    githubUrl: 'https://github.com/sumancpp/React-Projects/tree/main/Personal%20Property%20Rental',
    overview: 'Property discovery web app with dynamic listing categories.',
    order: 12,
  },
];
